### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by rbovard** [sitnyon/qgis-plugin-settings-manager#36]
- Hidden browser paths
  - [x] TODO: only generic paths
- WMS Cache
  - It cache only the GetCapabilities, not the data --> Nothing to do
- Copyright label
  - [x] TODO
- Paths to templates
  - [x] TODO: even if folder is empty

@tlesage Can you elaborate those points?

**Comment by tlesage** [comment]
* Hidden browser paths : 
Paths can be selectively hidden from the browser panel. We could mask our data sources and project like this : 

![hidden_browser_parth](https://cloud.githubusercontent.com/assets/4549659/17130630/d291c342-5319-11e6-96dc-a28bb637dd26.png)

* WMS Cache : 
QGIS will now cache WMS `GetCapabilities` requests so that on subsequent use response times will be quicker when using that service. By default the cache period is 24 hours, but you can adjust this in the `Network ` tab of the QGIS Settings dialog

* Copyright label : 

![copyright_label](https://cloud.githubusercontent.com/assets/4549659/17131017/a8688900-531b-11e6-9608-5eb007a05caf.png)

Is it relevant ? What do you think about that ?

* Paths to templates :  

We can now define custom paths that should be used for QGIS to find composer templates. But... 
... actually, we don't have composer templates.
